FROM node:18-alpine

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend ./frontend

WORKDIR /app/frontend

RUN npm run build

EXPOSE 5000

RUN npm install -g serve
CMD ["serve", "-s", "public"]