services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping")' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:
networks:
  app-network: